spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: db-changes-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    users: dbserver1.public.users
    orders: dbserver1.public.orders
